name: test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: amancevice/aws-sts-assume-role@main
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-arn: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: "GitHub-Action"
          duration-seconds: 900
